platform:ios,'8.0'

target  'Project' do
pod 'Masonry'
pod 'ReactiveCocoa', '~> 2.5'
pod 'CHNetworking'
pod 'CHProgressHUD'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'IQKeyboardManager'
pod 'SDBaseRequest'
pod 'CHImagePicker'
pod 'JSONModel'
pod 'HYBLoopScrollView'
pod 'CHWebView'

end

