platform:ios,'8.0'

target 'NewProject' do
  use_frameworks!

pod 'RxSwift'
pod 'RxCocoa'
pod 'Moya'
pod 'SwiftyJSON' 
pod 'Alamofire' 
pod 'CHProgressHUD'
pod 'CHImagePicker'
pod 'ObjectMapper'
pod 'AlamofireObjectMapper'
pod 'IQKeyboardManagerSwift', '4.0.5'
pod 'CHWebView'
pod 'Kingfisher'
pod 'SnapKit'

end
